[package]
name = "spokane_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
maud = { version = "0.26.0", features = ["axum"] }
axum = "0.7.5"
tokio = { version = "1.40.0", features = ["full"] }
