-- Add up migration script here
CREATE TABLE IF NOT EXISTS Meetups(
    MeetupId BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Title TEXT NOT NULL,
    BodyText TEXT NOT NULL,
    CreatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);